set nocompatible
set noswapfile
" increase buffer size
set viminfo='20,<1000,s1000
" autocomplete filename in command line mode
set wildmenu
" show file path name in the title bar
set title
" showbreaks
set showbreak=↪
" indent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent
autocmd! FileType c set cindent noexpandtab tabstop=8 shiftwidth=8 softtabstop=8
autocmd! FileType python set tabstop=4 shiftwidth=4 softtabstop=4

" start from the last cursor position
autocmd BufReadPost *
\ if line("'\"") > 0 && line ("'\"") <= line("$") |
\   exe "normal! g'\"" |
\ endif

" highlight space at the end of line
augroup HighlightTrailingSpaces
  autocmd!
  autocmd VimEnter,WinEnter,ColorScheme * highlight TrailingSpaces
  \ term=underline guibg=DarkGray ctermbg=DarkGray
  autocmd VimEnter,WinEnter * match TrailingSpaces /\s\+$/
augroup END

"keybinding
noremap j gj
noremap k gk
noremap gj j
noremap gk k

"my command
command RmTrailSpace %s/\s\+$//e

"NeoBundle
"set runtimepath+=~/.vim/bundle/neobundle.vim
"call neobundle#begin(expand('~/.vim/bundle/'))
"NeoBundleFetch 'Shougo/neobundle.vim'
"call neobundle#end()

filetype plugin indent on
