set nocompatible
set noswapfile
" increase buffer size
set viminfo='20,<1000,s1000
" autocomplete filename in command line mode
set wildmenu
" show file path name in the title bar
set title
" showbreaks
set showbreak=>\ 
" comment color
hi Comment ctermfg=blue

" indent
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

autocmd! FileType c set
      \ cindent
      \ noexpandtab
      \ tabstop=8
      \ shiftwidth=8
      \ softtabstop=8

autocmd! FileType python set
      \ tabstop=4
      \ shiftwidth=4
      \ softtabstop=4

autocmd! FileType java set
      \ tabstop=4
      \ shiftwidth=4
      \ softtabstop=4

autocmd! FileType xml set
      \ tabstop=4
      \ shiftwidth=4
      \ softtabstop=4

" start from the last cursor position
autocmd BufReadPost *
      \ if line("'\"") > 0 && line ("'\"") <= line("$") |
      \   exe "normal! g'\"" |
      \ endif

" highlight space at the end of line
augroup HighlightTrailingSpaces
  autocmd!
  autocmd VimEnter,WinEnter,ColorScheme * highlight TrailingSpaces
        \ term=underline guibg=DarkGray ctermbg=DarkGray
  autocmd VimEnter,WinEnter * match TrailingSpaces /\s\+$/
augroup END

" keybinding
"------------

let mapleader = "\<Space>"

" togle command mode with ;
noremap ; :

noremap j gj
noremap k gk
noremap gj j
noremap gk k

nnoremap cw ciw
nnoremap dw daw
nnoremap vw viw
nnoremap yw yiw

nnoremap c" ci"
nnoremap d" di"
nnoremap v" vi"
nnoremap y" yi"

nnoremap c' ci'
nnoremap d' di'
nnoremap v' vi'
nnoremap y' yi'

nnoremap c) ci)
nnoremap d) di)
nnoremap v) vi)
nnoremap y) yi)
nnoremap c( ca(
nnoremap d( da(
nnoremap v( va(
nnoremap y( ya(

nnoremap c} ci}
nnoremap d} di}
nnoremap v} vi}
nnoremap y} yi}
nnoremap c{ ca{
nnoremap d{ da{
nnoremap v{ va{
nnoremap y{ ya{

nnoremap c] ci]
nnoremap d] di]
nnoremap v] vi]
nnoremap y] yi]
nnoremap c[ ca[
nnoremap d[ da[
nnoremap v[ va[
nnoremap y[ ya[

nnoremap c> ci>
nnoremap d> di>
nnoremap v> vi>
nnoremap y> yi>
nnoremap c< ca<
nnoremap d< da<
nnoremap v< va<
nnoremap y< ya<

nnoremap ZZ <Nop>
nnoremap ZQ <Nop>
nnoremap Q  <Nop>

noremap <C-g> <Esc>
noremap! <C-g> <Esc>

" indent with tab
nnoremap <Tab> >>
nnoremap <S-Tab> <<
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

" format and remove trailing space
nnoremap = :s/\s\+$//e<CR>==
vnoremap = :s/\s\+$//e<CR>gv=

" bash like
noremap! <C-a> <Home>
noremap! <C-e> <End>
inoremap <C-u> <Esc>ld0i
inoremap <C-k> <Esc>lDa

inoremap <Nul> <C-x><C-o>

noremap <Left> <C-w>h
noremap <Down> <C-w>j
noremap <Up> <C-w>k
noremap <Right> <C-w>l
noremap <C-Right> <C-w>v
noremap <C-Up> <C-w>s
noremap <C-Down> <C-w>c
noremap <C-Left> <C-w>o

filetype plugin indent on
